sudo: false
language: python
python:
  - '3.5'
  - '3.6'
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
env:
  global:
    - DATABASE_URL=postgresql://localhost/flask_psi_test
    - TEST_DATABASE_URL=postgresql://localhost/flask_psi_test
    - TESTING="True"
services:
  - postgresql
before_script:
  - psql -U postgres -c 'CREATE DATABASE flask_psi_test;'
before_install:
  - pip install codecov
install:
  - pip install -r requirements/test.txt
  - pip install codeclimate-test-reporter
  - mv setup.cfg.template setup.cfg
  - mkdir -p app/static/uploaded
script:
  # - python manage.py test
  - nosetests tests --with-coverage --cover-erase --cover-branches --with-xunit --xunit-file=nosetests.xml
after_success:
  - export CODECLIMATE_REPO_TOKEN=b66ce794c42bc566d01713825caa2dfd117ba2b8e67e17dcb64ebb85dd2655ba
  - codeclimate-test-reporter
  - export BUILD_DATE_FORMAT="+%Y-%m-%d"
  - export BUILD_DATE=`date $BUILD_DATE_FORMAT`
  - echo "$TRAVIS_COMMIT $TRAVIS_BUILD_NUMBER $TRAVIS_BUILD_ID $TRAVIS_BRANCH $TRAVIS_TAG $BUILD_DATE"
  - echo "$TRAVIS_COMMIT $TRAVIS_BUILD_NUMBER $TRAVIS_BUILD_ID $TRAVIS_BRANCH $TRAVIS_TAG $BUILD_DATE" > swtag
  - codecov

deploy:
  - provider: heroku
    skip_cleanup: true
    api_key:
      secure: TE6DJdPpAU9bkW9G4+i8uZtegaQ2hCuXl4HcFOVSI+P1VSCuW2ESrQKpkOob4Ym8WEOwfLmCp0bzebModbkbJ1KpzxLS/KAmzr6crBJTPm04seKOKRXOjZeVZlp+nn9QvCA7OIFgdbDWeumH6+4DzR/rjvnfacJ8jvt5wm8nlvL57D7psr3CEIbTvsDdcTaKGlbaFnaXUTRoR3Lrc3ACqvNRAl3sXR1s4RBwKd+3cD3o/606IUeSCV2NUEs07JsJyQY3nTabdyiM5COxiE268aPE+BE3OqDRSESuIMBRhjmO7FW8QJfd+R0E3MDl/t/CPufkvC20OnM49sbDjQgXpijVga/znu32ZTC6a4Nq6bQlEWFiM01GbOKb4ZgGoqQhILxFW7LIJg+yiLz7I0FKc79o4o/hc3NL3z4tHZXjxtV7p7c86Db1W+mbGe1iwrnmxQN4T3hQFs4Nwm6mFEcBWkq1wQQ9F2m7Pm8Bt7Hg9w+90zNmcug8YyU4YdrHW0Uu/hmkGglrZJe/Cl1wM1ONCTOVRideKGMQigBudFXeuH6Ey0pMbp7dxH9y9Q0ZATex07QP/JtBNan+CSO0C0l8zUOs/TV1GSzCeYwc0V0sL4nNygmTArIq/0ZHJIJOLxjWvSDLPA4OqP0UL6TN9Z9QzoNlR74C45GxKbdsqDZBeYw=
    app: psi-dev
    on:
      repo: betterlife/psi
      all_branches: true
    run:
    - restart
  - provider: heroku
    skip_cleanup: true
    api_key:
        secure: TE6DJdPpAU9bkW9G4+i8uZtegaQ2hCuXl4HcFOVSI+P1VSCuW2ESrQKpkOob4Ym8WEOwfLmCp0bzebModbkbJ1KpzxLS/KAmzr6crBJTPm04seKOKRXOjZeVZlp+nn9QvCA7OIFgdbDWeumH6+4DzR/rjvnfacJ8jvt5wm8nlvL57D7psr3CEIbTvsDdcTaKGlbaFnaXUTRoR3Lrc3ACqvNRAl3sXR1s4RBwKd+3cD3o/606IUeSCV2NUEs07JsJyQY3nTabdyiM5COxiE268aPE+BE3OqDRSESuIMBRhjmO7FW8QJfd+R0E3MDl/t/CPufkvC20OnM49sbDjQgXpijVga/znu32ZTC6a4Nq6bQlEWFiM01GbOKb4ZgGoqQhILxFW7LIJg+yiLz7I0FKc79o4o/hc3NL3z4tHZXjxtV7p7c86Db1W+mbGe1iwrnmxQN4T3hQFs4Nwm6mFEcBWkq1wQQ9F2m7Pm8Bt7Hg9w+90zNmcug8YyU4YdrHW0Uu/hmkGglrZJe/Cl1wM1ONCTOVRideKGMQigBudFXeuH6Ey0pMbp7dxH9y9Q0ZATex07QP/JtBNan+CSO0C0l8zUOs/TV1GSzCeYwc0V0sL4nNygmTArIq/0ZHJIJOLxjWvSDLPA4OqP0UL6TN9Z9QzoNlR74C45GxKbdsqDZBeYw=
    on:
      repo: betterlife/psi
      tags: true
    app:
      master: psi-qa
    run:
    - restart
